# Development
dev:
  region: us-east-1
  userPoolId: ${env:USER_POOL_ID}
  userPoolClientId: ${env:USER_POOL_CLIENT_ID}
  sesFromEmail: ${env:SES_FROM_EMAIL, 'noreply@example.com'}

# Production
production:
  region: us-east-1
  userPoolId: ${env:USER_POOL_ID}
  userPoolClientId: ${env:USER_POOL_CLIENT_ID}
  sesFromEmail: ${env:SES_FROM_EMAIL}
